fit:
  seed_everything: 42
  model:
    pretrained_model: google/byt5-small
    use_pretraining: true
    learning_rate: 3.0e-05
    train_dataset: glue
    train_subdataset: mnli
    validation_set: validation_matched
    batch_size: 2
    max_length: 1024
    target_max_length: 5
    xlang_dataset_name: null
    xlang_subdataset_name: null
    xlang_validation_set: null
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-08
    adam_weight_decay: 0.0
    output_dir: ./output
  trainer:
    max_epochs: 5
    val_check_interval: 0.2
    gradient_clip_val: 1.0
    accumulate_grad_batches: 2
    precision: 32
    default_root_dir: ./checkpoints
    callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        log_momentum: false
    logger:
      class_path: pytorch_lightning.loggers.NeptuneLogger
      init_args:
        log_model_checkpoints: false
        prefix: training
    checkpoint_callback: null
    enable_checkpointing: true
    gradient_clip_algorithm: null
    process_position: 0
    num_nodes: 1
    num_processes: 1
    devices: null
    gpus: null
    auto_select_gpus: false
    tpu_cores: null
    ipus: null
    log_gpu_memory: null
    progress_bar_refresh_rate: null
    enable_progress_bar: true
    overfit_batches: 0.0
    track_grad_norm: -1
    check_val_every_n_epoch: 1
    fast_dev_run: false
    min_epochs: null
    max_steps: -1
    min_steps: null
    max_time: null
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    flush_logs_every_n_steps: null
    log_every_n_steps: 50
    accelerator: null
    strategy: null
    sync_batchnorm: false
    enable_model_summary: true
    weights_summary: top
    weights_save_path: null
    num_sanity_val_steps: 2
    resume_from_checkpoint: null
    profiler: null
    benchmark: false
    deterministic: false
    reload_dataloaders_every_n_epochs: 0
    reload_dataloaders_every_epoch: false
    auto_lr_find: false
    replace_sampler_ddp: true
    detect_anomaly: false
    auto_scale_batch_size: false
    prepare_data_per_node: null
    plugins: null
    amp_backend: native
    amp_level: null
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
    stochastic_weight_avg: false
    terminate_on_nan: null
  ckpt_path: null
