seed_everything: 42
data:
  class_path: data_qa.TydiQAGoldPModule
  init_args:
    tokenizer_name: "hugo/byt5-mono-bn-v1"
    batch_size: 6
    max_length: 2048
    max_target_length: 768
    train_language: bn
    dataloader_num_workers: 6
    validate_on:
      - bn
model:
  class_path: model_qa.QuestionAnsweringModel
  init_args:
    pretrained_model_name: "hugo/byt5-mono-bn-v1"
    pretrained_model_revision: "273dafaf63f799a4d6865aa482e1acaba83fd8dd"
    use_pretrained_weights: true
    from_flax: true
    max_target_length: 768
    metric_name: squad
optimizer:
  class_path: transformers.optimization.Adafactor
  init_args:
    lr: 0.0001
    scale_parameter: false
    relative_step: false
trainer:
  gpus: 1
  max_epochs: 10
  accumulate_grad_batches: 4
  precision: 32
  val_check_interval: 1.0
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: qa
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        filename: "baseline-qa-bn-bn-epoch={epoch}-step={step}-acc={val/bn/f1:.4f}"
        monitor: "val/bn/f1"
        mode: "max"
        save_last: true
        auto_insert_metric_name: false
    - class_path: pytorch_lightning.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: "val/bn/f1"
        mode: "max"
        patience: 3
