seed_everything: 42
data:
  class_path: data_nli.XnliDataModule
  init_args:
    tokenizer_name: "google/mt5-small"
    batch_size: 32
    max_length: 256
    max_target_length: 5
    train_language: en
model:
  pretrained_model_name: "google/mt5-small"
  use_pretrained_weights: true
  max_target_length: 5
optimizer:
  class_path: transformers.optimization.Adafactor
  init_args:
    lr: 0.0005
    scale_parameter: false
    relative_step: false
trainer:
  gpus: 1
  max_epochs: 3
  accumulate_grad_batches: 4
  precision: 32
  val_check_interval: 0.2
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
        project: nli
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        filename: "mt5-xnli-epoch={epoch}-step={step}-acc={val/avg_accuracy:.2f}"
        monitor: "val/avg_accuracy"
        mode: "max"
        save_last: true
        auto_insert_metric_name: false
