seed_everything: 42
data:
  class_path: data_nli.XnliDataModule
  init_args:
    tokenizer_name: "google/mt5-small"
    batch_size: 32
    max_length: 256
    max_target_length: 5
    train_language: en
model:
  pretrained_model_name: "google/mt5-small"
  use_pretrained_weights: true
  max_target_length: 5
optimizer:
  class_path: transformers.optimization.Adafactor
  init_args:
    lr: 0.001
    scale_parameter: false
    relative_step: false
trainer:
  gpus: 1
  max_epochs: 3
  precision: 32
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
        project: nli
