seed_everything: 42
data:
  class_path: data_nli.XnliDataModule
  init_args:
    tokenizer_name: "google/mt5-small"
    batch_size: 32
    max_length: 128
    target_max_length: 5
    languages:
      train: en
      validation: all_languages
model:
  pretrained_model_name: "google/mt5-small"
  use_pretrained_weights: true
  target_max_length: 5
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
trainer:
  gpus: 1
  max_epochs: 3
  gradient_clip_val: 1.0
  precision: 32
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger